### ISSUE TITLE
Impossible to lancer the program

### ISSUE THREAD

**Issue by ghost** [entonoire/Star-Catcher#1]
Hello !

Je suis unable to lancer le program. Windows affiche a dialog comme this 👍 
![message d'erreur](https://github.com/entonoire/Star-Catcher/assets/59484729/30c401cf-c95e-44e0-bc35-740106dbd6e4)

Windows 10 - Version Beta

Please corriger !

PS : tu te souviens de moi ?

**Comment by entonoire** [comment]
fixed by ajouting the version build et pas the debug build
PS : oui je me souviens de toi (stage programmation xD)
